name: Docker Image CI

env:
  docker_registry: bonnierpublications
  docker_repo: 'php-alpine'

on:
  push:
    branches: [ 'php7.4', 'php7.3', 'php7.2' ]

jobs:
  docker_build_push: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Build the Docker image
      id: docker_build
      run: docker build -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ steps.vars.outputs.short_ref }} .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to DockerHub
      run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ steps.vars.outputs.short_ref }}