name: php8.0 - Weekly Image Release

env:
  docker_registry: bonnierpublications
  docker_repo: 'php-alpine'
  docker_tag: 'php8.0'

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -f ${{ env.docker_tag }}/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }} -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}_${{ steps.date.outputs.date }} .
        
      - name: Push tag ${{ env.docker_tag }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}

      - name: Push tag ${{ env.docker_tag }}_${{ steps.date.outputs.date }} to DockerHub
        run: docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ env.docker_tag }}_${{ steps.date.outputs.date }}